<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW031C" failures="1" tests="1" name="runners.TestNGCucumberRunner2" time="12.681" errors="0" timestamp="2024-06-21T09:26:00 IST" skipped="0">
  <testcase classname="runners.TestNGCucumberRunner2" name="runScenario" time="12.681">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at steps.SignInOut.the_user_should_see_the_login_page(SignInOut.java:82)
at steps.SignInOut.the_user_enters_credentials_from_the_excel_file(SignInOut.java:50)
at âœ½.the user enters credentials from the excel file(file:///C:/Users/pushpanjali_g/eclipse-workspace/Test_Automation_Project/src/test/resources/features/batch2/SignInOutScenario2.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runners.TestNGCucumberRunner2 -->
